### ISSUE TITLE
test_inference.py is broken

### ISSUE THREAD

**Issue by 11415142513152119** [turboderp/exllamav2#83] opened 2023-10-02 19:58 UTC
Test_inference.py is giving me inappropriate results for models, like 5.8 when ooba's ppl tester gives me 4.9. Not sure what would be the cause of that.

**Comment by turboderp** [comment] 2023-10-02 21:33
Are you sure it's exactly the same test data?

**Comment by 11415142513152119** [comment] 2023-10-02 21:37
It's also wikitext but it might be different since ooba uses an arrow file and not parquet.

**Comment by turboderp** [comment] 2023-10-02 21:39
Wikitext has a number of different splits, and it also matters how much of the dataset you use and how you format it. Not sure how TGW does it, but it's probably not the same defaults.

**Comment by 11415142513152119** [comment] 2023-10-02 21:41
I'd have to somehow convert it to parquet to know for sure ig.

**Comment by 11415142513152119** [comment] 2023-10-07 20:50
I still don't know which datasets ooba uses. They're supposed to be wikitext2-v1 1.0.0 but the format and size are completely mismatched with the ones on HF.

**Comment by 11415142513152119** [comment] 2023-10-07 21:04
Ok, trying 5 rows (as in exl1) at equivalent context length instead of the two defaults finally gave me some good results.

**Comment by 11415142513152119** [comment] 2023-10-07 21:18
Ok, no, this script just doesn't want to work with me. Completely different results than ooba and I can't even get the same results as the one from the first repo. Too confusing.

**Comment by turboderp** [comment] 2023-10-07 23:44
I'm a little unclear on what you're trying to do. 

It does appear that there was an error setting the alpha value from the command line. Apparently I renamed the config entry at one point and forgot to update `model_init.init()` accordingly. It's been fixed with the latest commit. Thanks for noticing that. :+1: 

If it helps with the comparisons to ExLlamaV1, I wrote a script for it that implements the exact same tokenization and perplexity test logic as V2:

```python
from model import ExLlama, ExLlamaCache, ExLlamaConfig
from tokenizer import ExLlamaTokenizer
from generator import ExLlamaGenerator

import argparse, os, math, glob
import pandas, fastparquet
import torch
import torch.nn.functional as F

import sys
import json

parser = argparse.ArgumentParser(description = "Test inference on model")
parser.add_argument("-m", "--model_dir", type = str, help = "Model directory", default = "")
parser.add_argument("-ed", "--eval_dataset", type = str, help = "Perplexity evaluation dataset (.parquet file)")
parser.add_argument("-er", "--eval_rows", type = int, default = 128, help = "Number of rows to apply from dataset")
parser.add_argument("-el", "--eval_length", type = int, default = 2048, help = "Max no. tokens per sample")

args = parser.parse_args()

# Directory containing model, tokenizer, generator

model_directory =  args.model_dir

# Locate files we need within that directory

tokenizer_path = os.path.join(model_directory, "tokenizer.model")
model_config_path = os.path.join(model_directory, "config.json")
st_pattern = os.path.join(model_directory, "*.safetensors")
model_path = glob.glob(st_pattern)[0]

# Create config, model, tokenizer and generator

config = ExLlamaConfig(model_config_path)               # create config from config.json
config.model_path = model_path                          # supply path to model weights file

model = ExLlama(config)                                 # create ExLlama instance and load the weights
tokenizer = ExLlamaTokenizer(tokenizer_path)            # create tokenizer from tokenizer model file

cache = ExLlamaCache(model)                             # create cache for inference

def get_tokens(num_rows, length, filename, tokenizer):

    min_tokens = num_rows * length

    df = pandas.read_parquet(filename, engine = "fastparquet")
    df['concatenated'] = df.apply(lambda r: ' '.join([str(v) for v in r.values]), axis = 1)

    all_tokens = torch.empty((1,0), dtype = torch.long)

    for _, row in df['concatenated'].items():
        tokens = tokenizer.encode(row)
        all_tokens = torch.cat((all_tokens, tokens), dim = -1)
        if all_tokens.shape[-1] >= min_tokens: break

    if all_tokens.shape[-1] < min_tokens:
        print(f" ** Warning: Not enough sample data in {filename}")

    all_tokens = all_tokens.flatten()[:min_tokens]
    all_tokens = all_tokens.view((num_rows, length))

    num_print_tokens = 50
    data_sample = all_tokens[0, :num_print_tokens]
    print(f" -- First {num_print_tokens} tokens of dataset:")
    print(f"    {repr(tokenizer.decode(data_sample))}")
    data_sample = all_tokens[-1, -num_print_tokens:]
    print(f" -- Last {num_print_tokens} tokens of dataset:")
    print(f"    {repr(tokenizer.decode(data_sample))}")

    return all_tokens

# Test perplexity

if args.eval_dataset is not None:

    with torch.inference_mode():

        eval_dataset = args.eval_dataset
        eval_rows = args.eval_rows
        eval_length = args.eval_length

        print(f" -- Running perplexity test")
        print(f" -- Dataset: {eval_dataset}")
        print(f" -- Tokenizing eval data, {eval_rows} rows x {eval_length} tokens...")

        eval_tokens = get_tokens(eval_rows, eval_length, eval_dataset, tokenizer)

        print(f" -- Inference", end = "")
        sys.stdout.flush()

        logprob_sum = 0.0
        logprob_count = 0

        for i in range(eval_tokens.shape[0]):

            if i % 10 == 0: print(".", end = "")
            sys.stdout.flush()

            input_ids = eval_tokens[i:i+1, :]
            cache.current_seq_len = 0
            logits = model.forward(input_ids, cache, last_id_only = False)

            target_ids = input_ids[:, 1:].to("cuda:0")
            logits = logits[:, :-1, :].to("cuda:0")

            log_probs = F.log_softmax(logits, dim=-1)
            token_log_probs = log_probs.gather(-1, target_ids.unsqueeze(-1)).squeeze(-1)
            logprob_sum += token_log_probs.sum().item()
            logprob_count += target_ids.numel()

        print()

        mean_log_prob = logprob_sum / logprob_count
        perplexity = math.exp(-mean_log_prob)

        print(f" -- Evaluation perplexity: {perplexity:.4f}")

        xx = 0
```

I've confirmed that it gives the same results for the same model and dataset.

**Comment by 11415142513152119** [comment] 2023-10-07 23:47
Oh. Thank you. I'll check it out.

**Comment by turboderp** [comment] 2023-10-08 00:16
Something like:

```python test_inference.py -m <model> -ed <dataset> -l 6144 -er 16 -el 6144 -ra 1.7```

- `-l` sets the max sequence length for the model. Only relevant for the ppl test because it determines the size of the RoPE embedding table.
- `-ed` is the evaluation dataset
- `-er` is the number of rows to use from the dataset
- `-el` is the length of each row
- `-ra` sets the alpha value

**Comment by 11415142513152119** [comment] 2023-10-08 00:26
Now I get a "TypeError: q_attn_forward_1(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int, arg1: torch.Tensor, arg2: int, arg3: int, arg4: int, arg5: torch.Tensor, arg6: torch.Tensor, arg7: torch.Tensor, arg8: torch.Tensor, arg9: torch.Tensor, arg10: torch.Tensor) -> None" error with the script.

**Comment by turboderp** [comment] 2023-10-08 00:47
You probably have the prebuilt wheel installed? Cause I don't know what else would cause that. In any case probably best to stick with the JIT version and not running setup.py if you're cloning the repo.

**Comment by 11415142513152119** [comment] 2023-10-08 00:54
Got it running but nope, no, used your script and got 40ppl when it should be 4.5.
Two different datasets, same thing. Even increased alpha to make sure it's not it.

**Comment by turboderp** [comment] 2023-10-08 12:39
Could you explain exactly what you're doing to get this behavior?

**Comment by 11415142513152119** [comment] 2023-10-08 18:54
Exactly the command you gave with one of my merges and wikitext. It works perfectly on ooba so I dunno.

**Comment by turboderp** [comment] 2023-10-09 19:09
Does the model maybe require every sequence to begin in `<s>`? This seems to be a feature of some finetunes, that they either must see a BOS token, or they must *not* see a BOS token, in order to produce meaningful output.

**Comment by 11415142513152119** [comment] 2023-10-09 19:16
Maybe? But why would ooba do it okay, then? Or for that matter the exl1 script if it's a GPTQ version of it?

**Comment by turboderp** [comment] 2024-03-26 10:05
Closing some stale issues.

**Closed by turboderp** 2024-03-26 10:05 UTC
