### ISSUE TITLE
inference script starts producing bullshit at low temperatures

### ISSUE THREAD

**Issue by alimadelshin** [turboderp/exllamav2#50] opened 2023-09-21 11:53 UTC
inference script starts producing bullshit at low temperatures and the generation speed drops from 21 to ~1 token per second

**Comment by turboderp** [comment] 2023-09-21 16:15
Thanks, I missed that. Should be fixed now.

**Comment by Nikita-Sherstnev** [comment] 2023-09-22 12:38
Now at zero temperature model produces '每每每每每' symbols

**Comment by turboderp** [comment] 2023-09-22 15:09
Yes, zero temperature would be undefined behavior, since the logits are divided by the temperature before the softmax. But I guess the expected behavior is greedy sampling?

**Closed** 2023-10-05 09:25 UTC
